import "./globals.css";
import type { Metadata } from "next";
import { Poppins, Orbitron } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ProductProvider from "@/context/ProductContext";
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600"] });
const orbitron = Orbitron({ subsets: ["latin"], weight: ["700"] });
export const metadata: Metadata = {
  title: "Welcome to Gamezone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header logoFont={orbitron} />
        <ProductProvider>{children}</ProductProvider>
        <Footer logoFont={orbitron} />
      </body>
    </html>
  );
}
